#!/bin/bash

#if [ ! $# == 1 ]; then
#  echo "Usage: $0 robot@ip"
#  exit
#fi

scp restart_server stop_server start_server rhsay_server_respawn dj2_ip.conf rs485_server_respawn rs485_server press_return rhsay_server.py rs485_server_0068E837 rs485_server_0068E83A lubuntu@`cat dj2_ip.conf`:~
ssh lubuntu@`cat dj2_ip.conf` chmod +x stop_server restart_server start_server rhsay_server_respawn rs485_server_respawn rs485_server rhsay_server.py rs485_server_0068E837 rs485_server_0068E83A press_return

