#!/bin/bash

if [ ! $# == 1 ]; then
  echo "Usage: $0 robot@ip"
  exit
fi

scp dj2_ip.conf rs485_server_respawn rs485_server press_return rhsay_server.py rs485_server_0068E837 rs485_server_0068E83A $1:~
ssh $1 chmod +x dj2_ip.conf rs485_server_respawn rs485_server rhsay_server.py rs485_server_0068E837 rs485_server_0068E83A press_return

