#!/bin/bash
killall remserial
./remserial -d -r `cat dj2_ip.conf` -p 23000 -l /dev/rs485_1 /dev/ptmx &
./remserial -d -r `cat dj2_ip.conf` -p 23000 -l /dev/rs485_2 /dev/ptmx &
./remserial -d -r `cat dj2_ip.conf` -p 23000 -l /dev/rs485_3 /dev/ptmx &
./remserial -d -r `cat dj2_ip.conf` -p 23000 -l /dev/rs485_4 /dev/ptmx &
./remserial -d -r `cat dj2_ip.conf` -p 23000 -l /dev/rs485_5 /dev/ptmx &
sleep 1
chown shark /dev/rs485_1
chown shark /dev/rs485_2
chown shark /dev/rs485_3
chown shark /dev/rs485_4
chown shark /dev/rs485_5
